#
# Turn this into a basic template for HARP

# Site settings
title: "Youth Data Explorer"
description: "Using the OSDUHS survey, our goal is to provide reliable information about health risk behaviours and attitudes of Durham Region teens, tracking changes over time."
baseurl: "/PMO-data-explorer"
url: "https://durhamregionharp.github.io"
copyright_date: "2020"
lang: en-US
logo: "/assets/icon-128.png"

# Social settings
twitter:
  username: durhamepis
  card: summary

# User settings
username: Durham Region HARP
user_description: Epidemiologists making data fun again
user_title: Health Analytics Research and Policy
email: harp@durham.ca
facebook_username: durhamregionhealth
github_username: DurhamRegionHARP

# Build settings
markdown: kramdown
exclude: [
  'gulpfile.js',
  'package.json',
  'params.json',
  'Rakefile',
  'package-lock.json',
  'node_modules',
  'README.md',
  'pmo.json',
  'script/src'
  ]

# SASS settings
sass:
  style: compact

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Prose configuration
# Set ignore parameter to limit access to files we don't want available to edit
prose:
  rooturl: "_data"
  ignore: ['/css','/assests','/script','/theme_base','/','*.yml','*.html']
